language: python
python:
  - "2.7"
# commands to install dependencies
install: 
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r requirements-test.txt
# commands to run tests
script: 
  - py.test --cov=suseapi
  - pep8 suseapi
  - pylint --reports=n --rcfile=pylint.rc suseapi
  - pyflakes suseapi
after_success:
  - coveralls
